### ISSUE TITLE
Hito 2: Plantear herramientas a usar

### ISSUE THREAD

**Issue by ElenaMerelo** [fitplusplus/fithub#7]
Dejar por escrito el sistema de logging que vamos a utilizar, si vamos a emplear un servicio de configuración remota o servicios adicionales.

- Lenguaje: `Python`
- Logging: módulo `logging` de python (localmente) y PaperTrails o LogDNA (servidor).
- Servicio de configuración remota: `etcd`
- Base de datos: MongoDB al principio, posiblemente PostgreSQL en el futuro.

**Comment by antoniogamiz** [comment]
Vamos a realizar el proyecto en python, porque es un lenguaje de programación que nos permite crear un prototipado rápido a diferencia de otras opciones como C++.

**Comment by ElenaMerelo** [comment]
En el lado del cliente tendremos un catálogo que se descargará con la aplicación, con lo que un sistema de logging externo no tiene mucho sentido. Usaremos pues el módulo propio de python para logging, y, en caso de que permitamos el uso de un catálogo online, nos inclinaremos por PaperTrails o logDNA. Ambos tienen capas gratuitas, buenas opiniones y características. 

Al ser una aplicación básica, cualquiera de las dos será una buena opción. Seguramente usaremos PaperTrails, al tener experiencias previas con ella.

**Comment by ElenaMerelo** [comment]
Como servicio de configuración remota usaremos `etcd`, por su interfaz y configuración sencilla, además de la documentación disponible online, que facilitarán su empleo.

**Comment by antoniogamiz** [comment]
Aunque nos vendría bien usar una base de datos relacional porque nuestros datos están muy estructurados, vamos a optar por una opción más flexible como MongoDB, al adaptarse mejor a las cambios. Una vez tengamos la estructura de los datos clara, podríamos usar PostgresSQL y definir los esquemas que hagan falta.

**Comment by antoniogamiz** [comment]
Maybe en lugar de MongoDB podemos usar directamente JSON.
